// Lesson Data für Latein-8c
const defaultLessonData = {
  vocabData: [
    { la: 'agere', de: ['handeln', 'betreiben'], stf: 'ago, egi, actum', wt: 'V' },
    { la: 'audire', de: ['hören'], stf: 'audio, audivi, auditum', wt: 'V' },
    { la: 'capere', de: ['ergreifen', 'fassen'], stf: 'capio, cepi, captum', wt: 'V' },
    { la: 'colere', de: ['verehren', 'bebauen'], stf: 'colo, colui, cultum', wt: 'V' },
    { la: 'credere', de: ['glauben', 'vertrauen'], stf: 'credo, credidi, creditum', wt: 'V' },
    { la: 'dare', de: ['geben'], stf: 'do, dedi, datum', wt: 'V' },
    { la: 'debere', de: ['müssen', 'sollen'], stf: 'debeo, debui, debitum', wt: 'V' },
    { la: 'dicere', de: ['sagen', 'sprechen'], stf: 'dico, dixi, dictum', wt: 'V' },
    { la: 'docere', de: ['lehren', 'unterrichten'], stf: 'doceo, docui, doctum', wt: 'V' },
    { la: 'ducere', de: ['führen', 'ziehen'], stf: 'duco, duxi, ductum', wt: 'V' },
    { la: 'facere', de: ['machen', 'tun', 'handeln'], stf: 'facio, feci, factum', wt: 'V' },
    { la: 'habere', de: ['haben', 'halten', 'besitzen'], stf: 'habeo, habui, habitum', wt: 'V' },
    { la: 'intellegere', de: ['verstehen'], stf: 'intellego, intellexi, intellectum', wt: 'V' },
    { la: 'iubere', de: ['befehlen', 'anordnen'], stf: 'iubeo, iussi, iussum', wt: 'V' },
    { la: 'legere', de: ['lesen', 'sammeln'], stf: 'lego, legi, lectum', wt: 'V' },
    { la: 'ludere', de: ['spielen', 'scherzen'], stf: 'ludo, lusi, lusum', wt: 'V' },
    { la: 'mittere', de: ['schicken', 'loslassen'], stf: 'mitto, misi, missum', wt: 'V' },
    { la: 'movere', de: ['bewegen'], stf: 'moveo, movi, motum', wt: 'V' },
    { la: 'petere', de: ['aufsuchen', 'verlangen', 'fragen', 'angreifen'], stf: 'peto, petivi, petitum', wt: 'V' },
    { la: 'ponere', de: ['setzen', 'stellen', 'legen'], stf: 'pono, posui, positum', wt: 'V' },
    { la: 'putare', de: ['glauben', 'halten für'], stf: 'puto, putavi, putatum', wt: 'V' },
    { la: 'quaerere', de: ['suchen', 'fragen', 'bitten'], stf: 'quaero, quaesivi, quaesitum', wt: 'V' },
    { la: 'relinquere', de: ['verlassen', 'zurücklassen'], stf: 'relinquo, reliqui, relictum', wt: 'V' },
    { la: 'scire', de: ['wissen', 'kennen'], stf: 'scio, scivi, scitum', wt: 'V' },
    { la: 'scribere', de: ['schreiben'], stf: 'scribo, scripsi, scriptum', wt: 'V' },
    { la: 'sentire', de: ['fühlen', 'wahrnehmen'], stf: 'sentio, sensi, sensum', wt: 'V' },
    { la: 'tangere', de: ['berühren'], stf: 'tango, tetigi, tactum', wt: 'V' },
    { la: 'venire', de: ['kommen'], stf: 'venio, veni, ventum', wt: 'V' },
    { la: 'videre', de: ['sehen'], stf: 'video, vidi, visum', wt: 'V' }
  ],
  trChips: [],
  sentenceBlanks: [],
  fullLatinSentences: [],
  blankLatin: {},
  deLatMapping: [],
  contextMap: [],
  latinSegments: []
};
