// Lesson Data für Latein-8c
const defaultLessonData = {
  vocabData: [
    { latin: 'agere', bedeutung: 'handeln, (be)treiben', stammformen: 'ago, egi, actum' },
    { latin: 'audire', bedeutung: 'hören', stammformen: 'audio, audivi, auditum' },
    { latin: 'capere', bedeutung: '(er)greifen, fassen', stammformen: 'capio, cepi, captum' },
    { latin: 'colere', bedeutung: 'verehren, bebauen', stammformen: 'colo, colui, cultum' },
    { latin: 'credere', bedeutung: 'glauben, vertrauen', stammformen: 'credo, credidi, creditum' },
    { latin: 'dare', bedeutung: 'geben', stammformen: 'do, dedi, datum' },
    { latin: 'debere', bedeutung: 'müssen, sollen', stammformen: 'debeo, debui, debitum' },
    { latin: 'dicere', bedeutung: 'sagen, sprechen', stammformen: 'dico, dixi, dictum' },
    { latin: 'docere', bedeutung: 'lehren, unterrichten', stammformen: 'doceo, docui, doctum' },
    { latin: 'ducere', bedeutung: 'führen, ziehen', stammformen: 'duco, duxi, ductum' },
    { latin: 'facere', bedeutung: 'machen, tun, handeln', stammformen: 'facio, feci, factum' },
    { latin: 'habere', bedeutung: 'haben, halten, besitzen', stammformen: 'habeo, habui, habitum' },
    { latin: 'intellegere', bedeutung: 'verstehen', stammformen: 'intellego, intellexi, intellectum' },
    { latin: 'iubere', bedeutung: 'befehlen, anordnen', stammformen: 'iubeo, iussi, iussum' },
    { latin: 'legere', bedeutung: 'lesen; (auf)sammeln', stammformen: 'lego, legi, lectum' },
    { latin: 'ludere', bedeutung: 'spielen, scherzen', stammformen: 'ludo, lusi, lusum' },
    { latin: 'mittere', bedeutung: 'schicken, (los)lassen', stammformen: 'mitto, misi, missum' },
    { latin: 'movere', bedeutung: 'bewegen', stammformen: 'moveo, movi, motum' },
    { latin: 'petere', bedeutung: '(auf)suchen, verlangen, fragen, angreifen', stammformen: 'peto, petivi, petitum' },
    { latin: 'ponere', bedeutung: 'setzen, stellen, legen', stammformen: 'pono, posui, positum' },
    { latin: 'putare', bedeutung: 'glauben, halten für', stammformen: 'puto, putavi, putatum' },
    { latin: 'quaerere', bedeutung: 'suchen, fragen, bitten', stammformen: 'quaero, quaesivi, quaesitum' },
    { latin: 'relinquere', bedeutung: 'verlassen, zurücklassen', stammformen: 'relinquo, reliqui, relictum' },
    { latin: 'scire', bedeutung: 'wissen, kennen', stammformen: 'scio, scivi, scitum' },
    { latin: 'scribere', bedeutung: 'schreiben', stammformen: 'scribo, scripsi, scriptum' },
    { latin: 'sentire', bedeutung: 'fühlen, wahrnehmen', stammformen: 'sentio, sensi, sensum' },
    { latin: 'tangere', bedeutung: 'berühren', stammformen: 'tango, tetigi, tactum' },
    { latin: '(in)venire', bedeutung: '(erfinden), kommen', stammformen: '(in)venio, (in)veni, (in)ventum' },
    { latin: 'videre', bedeutung: 'sehen', stammformen: 'video, vidi, visum' }
  ],
  trChips: [],
  sentenceBlanks: [],
  fullLatinSentences: [],
  blankLatin: {},
  deLatMapping: [],
  contextMap: [],
  latinSegments: []
};
